Repository janosh/matbench-discovery, pull requests merged in 2024-07, with the labels that each got.

#111 Add new `/models/mace` page with formation energy and raw energy parity plots
  data/mp/eda_mp_trj.py
  data/wbm/eda_wbm.py
  matbench_discovery/enums.py
  matbench_discovery/preds.py
  matbench_discovery/slurm.py
  models/alignn/test_alignn.py
  models/alignn_ff/alignn_ff_relax.py
  models/alignn_ff/test_alignn_ff.py
  models/cgcnn/test_cgcnn.py
  models/chgnet/join_chgnet_results.py
  models/gnome/test_gnome.py
  models/mace/analyze_mace.py
  models/mace/join_mace_results.py
  models/megnet/test_megnet.py
  models/voronoi_rf/train_test_voronoi_rf.py
  models/wrenformer/test_wrenformer.py
  scripts/hist_classified_stable_vs_hull_dist_batches.py
  scripts/model_figs/hist_classified_stable_vs_hull_dist_models.py
  scripts/model_figs/parity_energy_models.py
  site/src/figs/mace-wbm-IS2RE-e-form-parity.svelte
  site/src/figs/mace-wbm-IS2RE-raw-energy-parity.svelte
  site/src/routes/models/mace/+page.svelte
  tests/test_data.py
  tests/test_plots.py
  tests/test_preds.py
  tests/test_slurm.py
Labels: analysis, reproducibility, fix

#113 Update MACE readme
  .gitignore
  models/mace/mace.yml
  models/mace/readme.md
  models/mace/train_mace.py
  tests/test_models.py
Labels: docs

#112 add SevenNet to Matbench Discovery leaderboard
  .gitignore
  matbench_discovery/__init__.py
  matbench_discovery/enums.py
  matbench_discovery/preds.py
  models/alignn/alignn.yml
  models/alignn_ff/alignn-ff.yml
  models/bowsr/bowsr.yml
  models/cgcnn/cgcnn+p.yml
  models/cgcnn/cgcnn.yml
  models/chgnet/chgnet.yml
  models/gnome/gnome.yml
  models/m3gnet/m3gnet.yml
  models/mace/analyze_mace.py
  models/mace/mace.yml
  models/mace/test_mace.py
  models/mattersim/mattersim.yml
  models/megnet/megnet.yml
  models/sevennet/2024-07-11-sevennet-preds-bad.csv.gz
  models/sevennet/2024-07-11-sevennet-preds-no-bad.csv.gz
  models/sevennet/2024-07-11-sevennet-preds.csv.gz
  models/sevennet/filter_bad_preds.py
  models/sevennet/join_results.py
  models/sevennet/sevennet.yml
  models/sevennet/test_sevennet.py
  models/sevennet/train_sevennet/convert_MPTrj2xyz.py
  models/sevennet/train_sevennet/pre_train.yaml
  models/sevennet/train_sevennet/train_sevennet.sh
  models/voronoi_rf/voronoi_rf.yml
  models/wrenformer/wrenformer.yml
  scripts/model_figs/compile_model_stats.py
  scripts/model_figs/metrics_tables.py
  scripts/model_figs/parity_energy_models.py
  site/src/figs/box-hull-dist-errors.svelte
  site/src/figs/cumulative-mae.svelte
  site/src/figs/cumulative-precision-recall.svelte
  site/src/figs/e-form-parity-models-5x2.svelte
  site/src/figs/e-form-parity-models-7x2.svelte
  site/src/figs/each-parity-models-7x2.svelte
  site/src/figs/hist-clf-pred-hull-dist-models-5x2.svelte
  site/src/figs/hist-clf-pred-hull-dist-models-7x2.svelte
  site/src/figs/hist-clf-true-hull-dist-models-5x2.svelte
  site/src/figs/metrics-table-first-10k.svelte
  site/src/figs/metrics-table-uniq-protos.svelte
  site/src/figs/metrics-table.svelte
  site/src/figs/roc-models.svelte
  site/src/figs/rolling-mae-vs-hull-dist-models.svelte
  site/src/figs/rolling-mae-vs-hull-dist-wbm-batches-mattersim.svelte
  site/src/figs/rolling-mae-vs-hull-dist-wbm-batches-sevennet.svelte
  site/src/lib/model-stats-10k.json
  site/src/lib/model-stats-uniq-protos.json
  site/src/lib/model-stats.json
  site/src/routes/preprint/+page.md
  tests/model-schema.yml
  tests/test_models.py
Labels: new model

#114 Refactor `Files`, `DataFiles` and `PredFiles` to be `StrEnums`
  changelog.md
  data/mp/build_phase_diagram.py
  data/mp/eda_mp_trj.py
  data/mp/get_mp_energies.py
  data/wbm/compare_cse_vs_ce_mp_2020_corrections.py
  data/wbm/compile_wbm_test_set.py
  data/wbm/eda_wbm.py
  matbench_discovery/__init__.py
  matbench_discovery/data.py
  matbench_discovery/energy.py
  matbench_discovery/preds.py
  models/alignn/test_alignn.py
  models/alignn/train_alignn.py
  models/alignn_ff/alignn_ff_relax.py
  models/alignn_ff/test_alignn_ff.py
  models/bowsr/join_bowsr_results.py
  models/bowsr/test_bowsr.py
  models/cgcnn/test_cgcnn.py
  models/cgcnn/train_cgcnn.py
  models/chgnet/analyze_chgnet.py
  models/chgnet/ctk_structure_viewer.py
  models/chgnet/test_chgnet.py
  models/m3gnet/join_m3gnet_results.py
  models/m3gnet/pre_vs_post_m3gnet_relaxation.py
  models/m3gnet/test_m3gnet.py
  models/mace/analyze_mace.py
  models/mace/join_mace_results.py
  models/mace/json_to_extxyz.py
  models/mace/test_mace.py
  models/mattersim/test_mattersim.py
  models/megnet/test_megnet.py
  models/sevennet/join_results.py
  models/sevennet/test_sevennet.py
  models/voronoi_rf/train_test_voronoi_rf.py
  models/voronoi_rf/voronoi_featurize_dataset.py
  models/wrenformer/analyze_wrenformer.py
  models/wrenformer/train_wrenformer.py
  scripts/analyze_model_failure_cases.py
  scripts/compute_struct_fingerprints.py
  scripts/model_figs/analyze_model_disagreement.py
  scripts/model_figs/metrics_tables.py
  scripts/project_compositions.py
  scripts/upload_to_figshare.py
  scripts/wbm_umap_projection.py
  tests/test_data.py
  tests/test_preds.py
Labels: refactor

#115 Add `n_estimators` to `model_metadata.yml`
  .pre-commit-config.yaml
  matbench_discovery/data.py
  models/alignn/alignn.yml
  models/bowsr/bowsr.yml
  models/cgcnn/cgcnn+p.yml
  models/cgcnn/cgcnn.yml
  models/chgnet/chgnet.yml
  models/gnome/gnome.yml
  models/m3gnet/m3gnet.yml
  models/mace/mace.yml
  models/mattersim/mattersim.yml
  models/megnet/megnet.yml
  models/sevennet/sevennet.yml
  models/voronoi_rf/voronoi_rf.yml
  models/wrenformer/wrenformer.yml
  pyproject.toml
  scripts/metrics-which-is-better.json
  scripts/metrics-which-is-better.yml
  scripts/model_figs/metrics_tables.py
  site/package.json
  site/src/app.d.ts
  site/src/figs/metrics-table-uniq-protos.svelte
  site/src/lib/ModelCard.svelte
  site/src/lib/model-schema.d.ts
  site/src/routes/models/+page.svelte
  tests/model-schema.yml
Labels: docs, site

#116 Update table caption for landing page
  .pre-commit-config.yaml
  matbench_discovery/enums.py
  matbench_discovery/models.py
  models/alignn_ff/alignn-ff.yml
  scripts/model_figs/metrics_tables.py
  site/src/figs/metrics-table-uniq-protos.svelte
  site/src/lib/CaptionedMetricsTable.svelte
  tests/test_enums.py
Labels: docs
